version: '3'

services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    command: python src/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app/src  # Adjusted volume mapping to reflect the src directory
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
